### ISSUE TITLE
Finding the last version of history with php 7.4

### ISSUE THREAD

**Issue by MalikWilliams1greher** [linuxserver/docker-nginx#100]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I need to deploy an application using php 7.4 (php8 is not supported in this program). Since linuxserver/nginx has been updated to 8.3 and hundreds of versions, how do I quickly find a historical version that supports 7.4?

### Reason for change

I'd like to find the latest old version, please.

**Comment by Roxedus** [comment]
1. Check the [changelog](https://github.com/linuxserver/docker-nginx#versions) for the image.
2. Assume 7.4 was the last before 8, thus you need a version prior to the rebase 3.14, note the date for the change.
3. Scroll trough the [releases](https://github.com/linuxserver/docker-nginx/releases)
4. Scroll and realize this is not quick.
5. Find something like [1.18.0-r15-ls136](https://github.com/linuxserver/docker-nginx/releases/tag/1.18.0-r15-ls136)
6. Open the release and browse the files at that [tag](https://github.com/linuxserver/docker-nginx/tree/1.18.0-r15-ls136)
7. Read [package_versions.txt](https://github.com/linuxserver/docker-nginx/blob/1.18.0-r15-ls136/package_versions.txt) and look for version. 
8. Find PHP [EOL](https://endoflife.date/php) list and bug app devs that this version shouldn't have been used for years
9. Do the same for [Alpine](https://endoflife.date/alpine), and understand this should not be used in production

**Comment by thespad** [comment]
You'll see that the last changelog entry before the switch to PHP8 was `Install nginx version from 3.14.`. If you search against the repo you'll see https://github.com/linuxserver/docker-nginx/pull/81 and that "This pull request first appeared in 1.20.2-r1-ls179" and there's your tag (there will be more between that and the PHP8 rebase but honestly at this age of image there's going to be little benefit in being a couple of tags more recent).

As above you absolutely should not be using a long EOL version of PHP in production but there tag is there nonetheless.

**Comment by MalikWilliams1greher** [comment]
> You'll see that the last changelog entry before the switch to PHP8 was `Install nginx version from 3.14.`. If you search against the repo you'll see #81 and that "This pull request first appeared in 1.20.2-r1-ls179" and there's your tag (there will be more between that and the PHP8 rebase but honestly at this age of image there's going to be little benefit in being a couple of tags more recent).
> 
> As above you absolutely should not be using a long EOL version of PHP in production but there tag is there nonetheless.

Is there a LTS version for php 7.4?

**Comment by Roxedus** [comment]
No, support for php 7.4 died 28 Nov 2022, as noted on the PHP [EOL](https://endoflife.date/php) list.
