### ISSUE TITLE
[BUG] memcached not loaded

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/docker-nginx#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while: [memcached](https://github.com/linuxserver/docker-nginx/blob/master/Dockerfile#L20) is installed
when I `docker exec nginx ps afux | grep memc`
nothing is return

also w3cache mention:
> The following memcached servers are not responding or not running:
> Database Cache: 127.0.0.1:11211.
> Object Cache: 127.0.0.1:11211.
> This message will automatically disappear once the issue is resolved.

### Expected Behavior

I expect memcached working on port 11211

### Steps To Reproduce

docker run -d \
  --name=nginx \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 80:80 \
  -p 443:443 \
  -v /path/to/nginx/config:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/nginx:latest
  
  

docker exec nginx ps afux | grep memc

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=nginx \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 80:80 \
  -p 443:443 \
  -v /path/to/nginx/config:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/nginx:latest
```

### Container logs

```bash
none
```

**Comment by Roxedus** [comment]
The service got removed [28.02.19](https://github.com/linuxserver/docker-nginx#versions)

**Comment by aptalca** [comment]
As Rox said, the `service` is removed, not the package. You can create a service if you like
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
