### ISSUE TITLE
[BUG] <title>How to connect database in a same docker network.

### ISSUE THREAD

**Issue by wswv** [linuxserver/docker-nginx#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to use the nginx as PHP runtime enviroument, I put the mybb in ngix docker directory "www", everything is fine, but when I tried to access dababase(used mariadb in a same docker network) following mybb installation process, it reports can't connect to database. there is no guidance or document how to configure the nginx docker to access database which outside the nginx docker. I'm not sure this is a right place to talk it here. but hope someone could help to support to solve it.

### Expected Behavior

the PHP application below nginx docker could access docker database in a same docker network.

### Steps To Reproduce

N/A right now

### Environment

```markdown
- OS:debian 12
- How docker service was installed:
docker and docker compose following guidance of docker official site
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
	
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - MYSQL_DATABASE=USER_DB_NAME #optional
      - MYSQL_USER=MYSQL_USER #optional
      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /path/to/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
```

### Container logs

```bash
N/A right now
```

**Comment by j0nnymoe** [comment]
Nothing to do with nginx. You'll be telling the web app to either use to help container name or your servers host IP.
