### ISSUE TITLE
Lua missing in this docker image

### ISSUE THREAD

**Issue by aaomidi** [linuxserver/docker-nginx#17]
I'm trying to use a lua block in my nginx configuration, however I'm receiving the following error:
```
 unknown directive "content_by_lua" in /config/nginx/site-confs/Site:20
```

I see that in https://github.com/linuxserver/docker-nginx/blob/master/Dockerfile#L22 you install lua so I'm not sure whats going on.

**Comment by aptalca** [comment]
Make sure your nginx conf has this line: https://github.com/linuxserver/docker-nginx/blob/master/root/defaults/nginx.conf#L4

**Comment by aaomidi** [comment]
Thanks!
