### ISSUE TITLE
Cannot reload nginx

### ISSUE THREAD

**Issue by dmce** [linuxserver/docker-nginx#20]
Hi

I cannot reload the configuration using

`docker exec -it nginx-server nginx -s reload`

as it results in

`nginx: [error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)`

**Comment by aptalca** [comment]
You're not supposed to be running commands inside the container.

Just restart the container and the config will be loaded

**Comment by dchevell** [comment]
I had the same issue. Restarting the container to pick up the config isn't a good solution - reloading nginx config should take a few milliseconds, restarting the whole container does a lot more than just reloading nginx (certificate checks, etc.) and brings everything down for 5-6 seconds. It's tens, if not hundreds of times slower, and in the case where you simply need to reload config it's like using a bulldozer to hammer a nail. 

For future searchers the right answer is to use `-c /config/nginx/nginx.conf` to point to the configuration file the container is using, e.g.

```
docker exec my_nginx_container nginx -s reload -c /config/nginx/nginx.conf
```
