### ISSUE TITLE
Feature: Add HTTP Substitutions Filter module

### ISSUE THREAD

**Issue by tynor88** [linuxserver/docker-nginx#30]
Please add [HTTP Substitutions Filter](https://www.nginx.com/products/nginx/modules/http-substitutions-filter/) to do dynamic javascript changes. [It can fix proxying of Resilio Sync](https://forum.resilio.com/topic/41989-setup-with-nginx-proxy/?do=findComment&comment=114060).

**Comment by aptalca** [comment]
That's a third party plugin with no dynamic module support so we can't add it.

But there is the regular sub filter that I believe does javascript substitutions.

http://nginx.org/en/docs/http/ngx_http_sub_module.html#sub_filter
