### ISSUE TITLE
Docker Hub image is not from an automated build

### ISSUE THREAD

**Issue by WyseNynja** [linuxserver/docker-nginx#4]
I wasn't sure if this was best opened as an issue here or done as a comment on https://hub.docker.com/r/linuxserver/nginx/, but I noticed that the build there is not an automated build.

Could this repo be migrated?

**Comment by sparklyballs** [comment]
We build our images (apart from 7 that were not migrated from automated builds) on our jenkins server and push them whole to the hub.
Images cannot be migrated between automated and manual, and we currently have no plans to change our setup.
