### ISSUE TITLE
Provide nginx build focused on secure proxying.

### ISSUE THREAD

**Issue by r-pufky** [linuxserver/docker-nginx#47]
Two main suggestions here:
* Run nginx as an underprivileged user by default.
* Run nginx only with proxy-focused modules, not webserver modules.

This will provide a more secure, default out-of-box LS nginx configuration.

Working assumptions:
* Most users consume this image to be used as a reverse proxy.
* Most users are blindly following Internet instructions.

## Underprivileged by default.
Run the nginx service with an unprivileged user by default; with UID/GID still able to be specified with the classic LS parameters (PUID/PGID). This will minimize impact in case of a compromise or bug in nginx or the modules themselves.

As it is a docker container, you can still map the external ports to the container correctly, so using unprivileged ports on nginx by default shouldn't be an issue here:
```docker
ports:
  - '80:8080'
  - '443:4343'
```
 
## Proxy only.
The working assumption of consumers of LS images a majority of home gamers setting up nginx solely for reversing proxying and exposing to the internet. The exposed footprint should be minimized focusing on functionality that would not be used.

Propose: remove _all_ PHP packages. from both this image and the underlying base image (even if that is removing them in this layer to produce the image.)

Effectively this is creating a LS nginx release that is focused on proxying with non-root privileges.

## Tagging
I'd suggest the following tags for this image:

`linxuserver/nginx-proxy`
`linuxserver/nginx-nophp`

**Comment by aptalca** [comment]
I understand and appreciate the request, but there are some issues with them

This nginx image is really meant to be a webserver and not a reverse proxy at all. The sister image `linuxserver/letsencrypt` is the one that is pulling double duty as webserver and reverse proxy. That image has many preset proxy confs for popular apps, where we accepted quite a few community additions, hosted here: https://github.com/linuxserver/reverse-proxy-confs 
Most of them work out of the box, some require further config.

We could create a tag for it without the webserver bits and php, but it would double the maintenance work going forward. We'll give that some thought.

With regards to underprivileged user, I believe nginx daemon has to run as privileged (not just for the ports but other issues as well), but the workers run as an underprivileged user which we set it to the PUID/PGID used.

**Comment by r-pufky** [comment]
No worries, thanks for the quick reply.

> This nginx image is really meant to be a webserver and not a reverse proxy at all. The sister image linuxserver/letsencrypt is the one that is pulling double duty as webserver and reverse proxy.

Ah, I didn't know that. I don't use that container (instead run compartmentalized reverse-proxy, with LE on a different container).

> We could create a tag for it without the webserver bits and php, but it would double the maintenance work going forward. We'll give that some thought.
> With regards to underprivileged user, I believe nginx daemon has to run as privileged (not just for the ports but other issues as well), but the workers run as an underprivileged user which we set it to the PUID/PGID used.

Correct -- for 80 and 443 you need to be running as root to open those ports; hence running as non-root you'll need to use something above 1024 for the daemon and the suggestion to mapping above.

Realistically, since it forks to a (non-root) nginx worker thread to serve requests, setting the main process to non-root is secondary to only including the nginx-mod* modules for a release. So really just a "pure" reverse-proxy only build.

**Comment by aptalca** [comment]
Closing this. Feel free to reopen if further discussion is needed.
