### ISSUE TITLE
add MSSQL support 

### ISSUE THREAD

**Issue by VNuhaan** [linuxserver/docker-nginx#52]
Hello linuxserver,

Can you add MSSQL support for PHP to the docker image?

Best regards,

Vincent

**Comment by aptalca** [comment]
Not sure if there is a module for that.
Here's all the sql related php modules I see: https://pkgs.alpinelinux.org/packages?name=php7*sql*&branch=v3.10&arch=x86_64

**Comment by VNuhaan** [comment]
Hi aptalca,

I think you are right with the pdo_odbc.

Regards,

Vincent
