### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by frankyw** [linuxserver/docker-nginx#67]
Can we get the version of php used bumped to 7.4.x please, Wordpress is now warning that 7.3.x is no longer recommended as it is not the current stable version. Thank you.

<img width="862" alt="Screen Shot 2020-06-28 at 10 09 51 AM" src="https://user-images.githubusercontent.com/2604571/85949985-f1370780-b927-11ea-996d-52e64ce05df3.png">

**Comment by CHBMB** [comment]
We're constrained to the PHP version in Alpine 3.12.

https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/php7

**Comment by frankyw** [comment]
@CHBMB I see, and also that Alpine 3.12 is the latest stable... :)

Will close this issue then, thanks for the response.
