### ISSUE TITLE
add php7-gmp

### ISSUE THREAD

**Issue by plr20** [linuxserver/docker-nginx#72]
Can `php7-gmp` be included in the image? FreshRSS Google Reader API won't work without it.

**Comment by Roxedus** [comment]
Additions to this image wont show up in our freshrss image

**Comment by plr20** [comment]
I was using the regular install of dropping the files into the nginx docker container, not using the official FreshRSS image.

**Comment by Roxedus** [comment]
> Not using the LS FreshRSS image. 

https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
