### ISSUE TITLE
Upgrade to Nginx 1.19.3+

### ISSUE THREAD

**Issue by sarbian** [linuxserver/docker-nginx#75]
## Desired Behavior
Could you upgrade to Nginx 1.19.3+?
The current version does not support the [proxy_cookie_flags](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_flags) directive. This would help a lot when trying to proxy site that set the SameSite cookie attribute to value that are no compatible with iframe.
The version is available in Alpine.

## Current Behavior
The current version only has the proxy_cookie_path which does not allow to replace an existing cookie value.

## Alternatives Considered
None

**Comment by j0nnymoe** [comment]
They're availble in alpine yes but not currently for v3.13: https://pkgs.alpinelinux.org/packages?name=nginx&branch=v3.13

**Comment by sarbian** [comment]
Thanks for the detailed reply. I will wait for Alpine 3.14 to be available and used.
