### ISSUE TITLE
Docker version not incremented (still 1.20.2) despite modification that altered functionality.

### ISSUE THREAD

**Issue by lucenelletenebre** [linuxserver/docker-nginx#84]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I expect that if you do ANY change in the code, the docker version should be incremented.

## Current Behavior
I was running docker version 1.20.2 (FROM linuxserver/nginx:1.20.2) without any problem since the beginning of this year, but since a couple of weeks ago my testing script started to report errors. I spend a looooong time trying to debug the issue and I discovered that someone decided to change the name of the default site inside /config/nginx/site-confs from "default" to "default.conf".
In my specific use, I have a script that substituted the default file with my dedicated configuration used for just testing.
I will be onest, I like this choise, but please, this should have been called version 1.20.3!
Instead the version 1.20.2 was overwritten, making debugging this issue very very difficult.

## Steps to Reproduce
I do not know how to reproduce it, because I do not know were the old version 1.20.2 is now (if it still exist)

## Environment
**OS:** Debian 11
**CPU architecture:** x86_64/
**How docker service was installed:** 

from official repo https://download.docker.com/linux/ubuntu

## Command used to create docker container (run/create/compose/screenshot)

FROM linuxserver/nginx:1.20.2

## Docker logs

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
Setting resolver to  127.0.0.11
Setting worker_processes to 4
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
............+++++
...+++++
writing new private key to '/config/keys/cert.key'
-----
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/70-outdated
cont-init: info: /etc/cont-init.d/70-outdated exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] nginx_runscript.sh: executing...
**** LUCENELLETENEBRE MOD INSTALLATION ****
rm: cannot remove '/config/nginx/site-confs/default': No such file or directory
[custom-init] nginx_runscript.sh: exited 0
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by j0nnymoe** [comment]
You pinned the nginx version, changing it to 1.20.3 wouldn't be correct. Which will always get updated to the with the latest baseimage. If you wanted to pin so there wasn't any changes, you need to state an `-lsXXX` number on the end aswell.

**Comment by lucenelletenebre** [comment]
so... at that point I should just pin the sha version and be done with it... I just found strange that I can have the same tag version with such a huge difference (so pretty much is useless to pin to 1.20.3) but ok, your project, your rules. I thought it was an error...

**Comment by j0nnymoe** [comment]
The point of those version tags is for people that don't want automatic software upgrades but want to maintain any baseimage updates/upgrades we do. We also posted this notice 2 weeks ago regarding the changes for this container: https://info.linuxserver.io/issues/2022-08-20-nginx-base/

**Comment by lucenelletenebre** [comment]
Thank you very much. Sorry to have bothered you about this, expecially since there is an annoucement about the modification, but as you can immagine is very difficult to read and keep up with everything if there is no issue! Now that I know more about how you manage the versions I will adapt my workflow. Please continue to keep up the good work!

**Comment by j0nnymoe** [comment]
You're welcome. Yea we understand it's hard to keep up with news/changes etc. We do try our best to get any information out for upcoming changes. The site I linked above is what we use to announce any major changes to our containers :).

**Comment by nemchik** [comment]
What you're looking for is the tag `1.20.2-r1-ls191` which is made up of 3 pieces of information.
- `1.20.2` the nginx version
- `r1` the Alpine package version
- `ls191` our lsio package version

Our package version can increase when we make changes to the image, or when our build pipeline updates underlying dependencies.

The sha tag is a pretty surefire way to use an exact image, but the full release tag above should be fairly similar. Once published, we generally don't re-push using the exact combination of numbers (our package build number should increase if we rebuild).
