### ISSUE TITLE
Ioncube Mod not working with PHP8.0

### ISSUE THREAD

**Issue by poiy23** [linuxserver/docker-nginx#85]
Hi i would like to use the MOD Ioncube but unfortunately it doesnt work with the current php Version. Is it possible to update PHP to the current version?

------------------------------

## Expected Behavior
NGINX should work with Ioncube again

## Current Behavior
Ioncube MOD doesnt work with current PHP Version 8.0

## Environment
Unraid
CPU architecture:  x86_64
How docker service was installed: Via CA

**Comment by nemchik** [comment]
It actually looks like the mod SHOULD work, however https://www.ioncube.com/loaders.php don't have php 8.0 files included in their downloads. They skipped 8.0 and went from 7.4 to 8.1.

**Comment by nemchik** [comment]
FYI, we updated our image here https://github.com/linuxserver/docker-nginx/pull/86 which included PHP 8.1 and should allow the mod to work (at least until it's time to move to php 8.2).
