### ISSUE TITLE
[FEAT] Allow me to set PUID and GUID to root.

### ISSUE THREAD

**Issue by colaH16** [linuxserver/docker-nginx#90]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

If I set the PUID or GUID to 0, I will see the following error.
`[pool www] please specify user and group other than root`
add options to run php-fpm with -R options

### Reason for change

I am using docker as rootless.
Inside the container, a file should be created with uid=0.
This will allow me to edit files without sudo on the host.

**Comment by colaH16** [comment]
As an alternative, I set the following in the docker-compose.yml to run as root.

entrypoint: sh -c "sed  -i 's|exec /usr/sbin/php-fpm81 -F|exec /usr/sbin/php-fpm81 -FR|g' /etc/s6-overlay/s6-rc.d/svc-php-fpm/run; /init"

**Comment by aptalca** [comment]
We do not support what you're doing. But you can see this article to see more proper ways to accomplish that: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
