### ISSUE TITLE
ARM32... why :(

### ISSUE THREAD

**Issue by IMNotMax** [linuxserver/docker-nginx#95]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

You used to support the arm32. Like me, probably a lot of people use old raspberry pi to enjoy DIY.

Why did you stop ? and more over, why did you put arm64 image in the arm32:latest version.

I think I will have to learn how to correctly build the image myself.

### Reason for change

Lot of arm32 devices in the wild.

**Comment by nemchik** [comment]
https://www.linuxserver.io/blog/a-farewell-to-arm-hf

This should answer your question.

**Comment by j0nnymoe** [comment]
Following links explains it all: 

Blog post: https://www.linuxserver.io/blog/a-farewell-to-arm-hf

Notices: https://info.linuxserver.io/issues/2023-06-06-armhf/ / https://info.linuxserver.io/issues/2023-05-06-armhf/ / https://info.linuxserver.io/issues/2023-04-06-armhf/

**Comment by IMNotMax** [comment]
Thank you for these answers !

**Comment by Roxedus** [comment]
If you venture down the path of maintaining your own image, you too will notice the lack of upstream support down the line.
